### PR TITLE
Add direction entries to avoid Snowball array overrun

### PR DESCRIPTION
**Pull request by angstsmurf**
This seems to trigger in at least the ZX Spectrum version of Snowball found at https://www.ifarchive.org/if-archive/games/spectrum/level9.zip (SNA/V3/SNOWBALL.SNA).

The game seems to work fine after this fix, but I haven't tested other games thoroughly and I don't understand the code well enough to tell if there might be any side effects.

### CODE REVIEW

**Comment by steve-arnold** [comment]
I am not sure of the purpose of the exitreversaltable but it normally has 15 entries from 1 - 15 corresponding to the directions ; north (1), northeast (2), east (3), south (4), southeast (5), southwest (6), west (7), northwest (8), up (9), down (10), in (11), out (12), across (13), jump (15)

L9BYTE exitreversaltable[16] = { 0x00,0x04,0x06,0x07,0x01,0x08,0x02,0x03,0x05,0x0a,0x09,0x0c,0x0b,0xff,0xff,0x0f };
This table contains the reverse direction corresponding to each direction for example -
north (1) exitreversaltable[1] = 4 i.e. south (4).
southeast (5) exitreversaltable[5] = 8 i.e. northwest (8).
etc.
Now entries 13 and 14 have 0xff which presumably means no reverse and entry 15 references itself.

Using a disassembler on the snowball file reveals there are additional directions; backward (16), forward (17), left (18), right (19). These are the values which cause the array to be read out of bounds. I would suggest a revision of the table to be with 0xff in the additional places -
 
L9BYTE exitreversaltable[0] = { 0x00,0x04,0x06,0x07,0x01,0x08,0x02,0x03,0x05,0x0a,0x09,0x0c,0x0b,0xff,0xff,0x0f,0xff,0xff,0xff,0xff };

Other games which use the normal 15 direction commands will be unaffected by this change.
What do you think?

**Comment by angstsmurf** [comment]
Sounds great. I'll revise the pull request with your change. Thanks for looking into this!

**Comment by angstsmurf** [comment]
Done.

**Comment by steve-arnold** [comment]
Hi,
Thanks for that revision. I am trying to learn how the Level 9 system works. I enjoyed playing them in the 1980s on my Nascom II and marveled at the amount of text which could be included.

Incidentally, the files for  Snowball and 8 other games in BBC format are available at https://github.com/hoglet67/AtomSoftwareArchive/tree/master/level9

They play on the Level9 emulator too.

Regards,
Steve

**Comment by steve-arnold** [comment]
Sorry to be a pain, but looking at the file SNOWBALL.ASM.ORIG from https://github.com/hoglet67/AtomSoftwareArchive/tree/master/level9 which is, I believe, a disassembly of the Acorn (BBC) version of snowball, it appears that the additional four entries in the array should be 0x00.

The relevant section starts at line 3249-
```
.L7335
        EQUB    $00,$04,$06,$07,$01,$08,$02,$03
        EQUB    $05,$0A,$09,$0C,$0B,$FF,$FF,$0F
        EQUB    $00,$00,$00,$00

```
So, at least in the BBC version of the data, the additional mappings in the array should be 00 NOT 0xff as I initially stated. I have not checked against the .sna file.

Steve

**Comment by angstsmurf** [comment]
Interesting. Actually looks like it is `0x7e, 0x23, 0xfe, 0xe0` in the SNOWBALL.SNA file. At least these are the values that follow the others.

EDIT: Also, in the original Spectrum interpreter, relative directions seem to be implemented. FORWARD starts out as a synonym of NORTH, RIGHT is EAST and so on, but if you go right (or east) FORWARD becomes EAST and RIGHT becomes SOUTH.

EDIT 2: This works the same in the Level9 interpreter (this reimplementation) as well.

**Comment by DavidKinder** [comment]
It seems unlikely that 0x7e, 0x23, 0xfe, 0xe0 are really the correct values: they ought to be indexes within the table, so in the range 0 - 0x14. All zeroes seems more likely to work. Possibly more investigation is needed to see what actually happens with different values when used with commands like "forward" in Snowball.

**Comment by angstsmurf** [comment]
Heh. You're right, I didn't look at what the code is actually doing. Changed it back to four zeroes. It would be interesting to know how this works in the original Spectrum interpreter.

**Comment by DavidKinder** [comment]
After thinking about this for a while, I've gone back to feeling that the extra entries in exitreversaltable should be 0xff. A value of 0xff definitely means "don't match any direction", you can see that from the code in exit1() after d6 is set to a value from exitreversaltable, the only use of d6 then is

	if (((*d4)&0x10)==0 || ((*d4)&0xf)!=d6) a0++;

Since *d4 is anded with 15, it can never match d6 if d6 contains a value >15. This is a bit more obvious from more recent Level9 work where the code is a bit clearer, e.g. https://github.com/ajgbarnes/level9/blob/main/level9.py, who has also gone with 0xff for the extra entries in that table.

Anyway, I've gone with the change in commit a1f748dccd3ec82c484095e24f18816089d84f2f.

**Comment by angstsmurf** [comment]
For what it is worth, I disassembled the SNA file. It is clear that the original code only uses a 16-byte table for reverse directions and that the four following bytes I mentioned are in fact the beginning of a function (beginning at address 0xdded).

**Comment by angstsmurf** [comment]
It is also somewhat interesting to compare [the `exit1()` function](https://github.com/DavidKinder/Level9/blob/3472427a30fcd17bfa33051cceaec558474fbd7a/level9.c#L2876-L2922) to what Ghidra makes of the corresponding Z80 code, mainly because of how similar they are. (I've renamed the variables in Ghidra to match `exit1()`.)

It is clear that the current Level9 interpreter code very closely matches the disassembly, so it would be expected that most bugs in the current codebase also can be found in the original machine code. By stepping through the original Z80 code, I can confirm that it also reads four bytes outside the bounds of the array.

```
byte exit1(byte d6, byte d7)
{
  byte d0;
  byte d1;
  byte *a0;
  
  a0 = absdatablock;
  for (d1 = d7 - 1; d1 != 0; d1 = d1 - 1) {
    do {
      d0 = *a0;
      a0 = a0 + 2;
    } while ((d0 & 0x80) == 0);
  }
  while( true ) {
    if ((*a0 & 0xf) == d6) {
      return *a0;
    }
    if ((*a0 & 0x80) != 0) break;
    a0 = a0 + 2;
  }
  a0 = absdatablock;
  while ((((*a0 & 0x10) == 0 || ((*a0 & 0xf) != exitreversaltable[d6])) || (a0[1] != d7))) {
    d0 = *a0;
    a0 = a0 + 2;
    if (d0 == 0) {
      return 0;
    }
  }
  return *a0;
}
```

**Comment by DavidKinder** [comment]
Yes, it looks a lot like this feature got hacked into the original codebase at some point, for some of the interpreters, but led to bugs ever after. For 1980s micros reading four extra bytes off a table wouldn't have any noticeable effect.

**Pull request closed without merging**
